### ISSUE TITLE
Add mobile support.

### ISSUE THREAD

**Issue by JunielKatarn** [maxton/Jam.NET#27]
It would be very convenient for the app to run in mobile platforms, such as Windows Universal iOS and Android.
I already have ongoing work on this at https://github.com/JunielKatarn/Jam.NET/tree/mobile.

Considerations:

- The UI must be fully re-implemented. The current .NET Desktop (Windows.Forms) code can't be reused on mobile.
- Xamarin.Forms provides a viable framework to code once and deploy to the three mobile platforms.
- Xamarin.Forms relies on PCLs (stripped-down .NET framework libraries, which have many limitations in terms of API access as opposed to regular .NET).

**Comment by maxton** [comment]
I haven't looked into the iOS/Android .NET support in a while, but last I knew, Xamarin.Forms is nonfree. 

Is Xamarin.Forms and related libraries/tooling free now that Microsoft has purchased the company, or is it still nonfree?

**Comment by JunielKatarn** [comment]
It is free as of Visual Studio 2017. See https://www.visualstudio.com/vs/compare/
Only some advanced tooling/profiling features require paid versions.

**Comment by maxton** [comment]
Nice - [Xamarin Live](https://www.xamarin.com/live) now allows you to build and run iOS *and* Android apps from VS2017 on a windows PC. This should make development easier.

Anyway, I think for audio on iOS it might end up being simplest to just use Xamarin's iOS framework bindings, like Xamarin.iOS.AudioToolbox etc... there's a cross-platform plugin called MediaManager but that is for high-level playing of MP3s and such, not adequate for what Jam.NET needs. For android, I assume they'll have similar audio APIs.

**Comment by JunielKatarn** [comment]
Yeah, in the end, I think I'll end up contributing to one of the Audio libraries myself, to add those iOS bridges.

If you have the time, take a look at my mobile branch. It's at a very early stage, but it's easy to run using the UWP variant. The UI is fully shared between Windows and iOS.

**Comment by JunielKatarn** [comment]
Solved for iOS, macOS, Android and UWP at https://github.com/JunielKatarn/Unjammit/tree/xplat .
